#!/usr/bin/env bash
# One-time setup for a named Cloudflare Tunnel (persistent, not trycloudflare).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$ROOT/cloudflared/config.yml"
EXAMPLE="$ROOT/cloudflared/config.yml.example"
TUNNEL_NAME="grok-bot-lobby"
CREDS_DIR="${CLOUDFLARED_HOME:-$HOME/.cloudflared}"

usage() {
  cat <<'EOF'
Usage: npm run tunnel:setup -- [--hostname lobby.example.com] [--zone example.com]

Creates a named Cloudflare Tunnel, routes DNS (when --hostname + --zone given),
writes cloudflared/config.yml, and prints .env.local lines.

Prerequisites:
  - cloudflared installed (brew install cloudflared)
  - Cloudflare account with a zone (for custom hostname)

Steps performed:
  1. cloudflared tunnel login        (browser, once per machine)
  2. cloudflared tunnel create       (skipped if tunnel already exists)
  3. cloudflared tunnel route dns    (when hostname provided)
  4. Write cloudflared/config.yml
EOF
}

HOSTNAME=""
ZONE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --hostname) HOSTNAME="$2"; shift 2 ;;
    --zone) ZONE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared not found. Install: brew install cloudflared" >&2
  exit 1
fi

mkdir -p "$CREDS_DIR"

if [[ ! -f "$CREDS_DIR/cert.pem" ]]; then
  echo "==> Log in to Cloudflare (browser opens once)..."
  cloudflared tunnel login
fi

TUNNEL_ID=""
if cloudflared tunnel list 2>/dev/null | awk '{print $1}' | grep -qxE '[0-9a-f-]{36}'; then
  TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v name="$TUNNEL_NAME" '$2 == name {print $1; exit}')"
fi

if [[ -z "$TUNNEL_ID" ]]; then
  echo "==> Creating tunnel: $TUNNEL_NAME"
  create_out="$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)"
  echo "$create_out"
  TUNNEL_ID="$(echo "$create_out" | sed -n 's/.*Created tunnel .* with id \([0-9a-f-]\{36\}\).*/\1/p')"
  if [[ -z "$TUNNEL_ID" ]]; then
    TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v name="$TUNNEL_NAME" '$2 == name {print $1; exit}')"
  fi
fi

if [[ -z "$TUNNEL_ID" ]]; then
  echo "Could not determine tunnel UUID for $TUNNEL_NAME" >&2
  exit 1
fi

CREDS_FILE="$CREDS_DIR/$TUNNEL_ID.json"
if [[ ! -f "$CREDS_FILE" ]]; then
  echo "Credentials file missing: $CREDS_FILE" >&2
  echo "Re-run: cloudflared tunnel create $TUNNEL_NAME" >&2
  exit 1
fi

if [[ -z "$HOSTNAME" ]]; then
  read -r -p "Public hostname (e.g. lobby.example.com): " HOSTNAME
fi

if [[ -n "$HOSTNAME" && -n "$ZONE" ]]; then
  echo "==> Routing DNS: $HOSTNAME -> $TUNNEL_NAME"
  cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME"
elif [[ -n "$HOSTNAME" ]]; then
  echo "==> Routing DNS: $HOSTNAME -> $TUNNEL_NAME"
  cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || {
    echo ""
    echo "DNS route failed. Add manually in Zero Trust -> Networks -> Tunnels -> $TUNNEL_NAME -> Public Hostname"
    echo "  Hostname: $HOSTNAME"
    echo "  Service: http://127.0.0.1:4521"
  }
fi

if [[ -z "$HOSTNAME" ]]; then
  HOSTNAME="lobby.example.com"
  echo "No hostname set — edit cloudflared/config.yml before going live."
fi

cat > "$CONFIG" <<EOF
# Generated by scripts/setup-tunnel.sh — named tunnel (persistent)
tunnel: $TUNNEL_ID
credentials-file: $CREDS_FILE

ingress:
  - hostname: $HOSTNAME
    service: http://127.0.0.1:4521
  - service: http_status:404
EOF

PUBLIC_URL="https://${HOSTNAME}"

echo ""
echo "==> Wrote $CONFIG"
echo ""
echo "Add to .env.local (then restart npm run dev):"
echo "LOBBY_PUBLIC_URL=$PUBLIC_URL"
echo "NEXT_PUBLIC_LOBBY_PUBLIC_URL=$PUBLIC_URL"
echo ""
echo "Start tunnel:  npm run tunnel"
echo "Install launchd: npm run tunnel:install"
echo "Join link:     $PUBLIC_URL/join/CODE  (create an event in the lobby to get CODE)"
echo ""
echo "Tunnel ID: $TUNNEL_ID (fixed — survives restarts when using launchd)"
